# Generated by Django 4.2.7 on 2025-01-23 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='image',
        ),
    ]
