# Generated by Django 5.1.5 on 2025-02-02 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='svg_file',
        ),
        migrations.AddField(
            model_name='state',
            name='region_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='svg_path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='abbreviation',
            field=models.CharField(max_length=2, unique=True),
        ),
    ]
