# Generated by Django 5.1.5 on 2025-02-02 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0004_remove_state_svg_file_state_region_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='svg_path',
        ),
        migrations.AddField(
            model_name='state',
            name='svg_file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='abbreviation',
            field=models.CharField(max_length=2),
        ),
    ]
