# Generated by Django 5.1.5 on 2025-02-03 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0005_remove_state_svg_path_state_svg_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='svg_file',
        ),
        migrations.AddField(
            model_name='state',
            name='svg_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
